[quote.epigraph, , 1 Thess. 5:21]
____
Examinadlo todo; retened lo bueno.
____

[short="Salgan de Babilonia"]
== Salgan de Babilonia / Un Llamado a la Verdadera Adoración

[.blurb]
=== Dirigido a los profesantes de religión de este día, por uno que por mucho tiempo fue un profesante del Cristianismo, pero que no conoció el poder, hasta que le agradó al Señor, mediante el ministerio y escritos del pueblo llamado Cuáqueros, dirigirlo al único lugar donde el poder puede experimentarse, es decir, al interior.

[.centered]
Lo siguiente es una compilación
de tres cartas escritas por John Spalding el año previo a su muerte,
sucedida a los 29 años, dirigida a los amados amigos y
compañeros profesantes del cristianismo, que entonces asistían a la
Iglesia de Saint Giles, en Reading.

[.asterism]
'''

Amigos, en algunas ocasiones, desde que me separé de su comunión,
mi mente ha estado muy inquieta deseando un avance real
en ustedes en el espíritu y poder de esa religión que profesan.
Al estar persuadido de que hay algunos entre ustedes
que realmente desean conocer la verdad,
siento un renovado interés de saludarlos, en una medida, espero,
del verdadero amor del evangelio, y de ofrecerles para la seria consideración de ustedes,
las razones que me indujeron a separarme de su sociedad.

Amigos, en verdad había muchos lazos que me unían a ustedes,
y por un tiempo considerable,
estuve muy poco dispuesto a creer que esas cosas
en las que me había ocupado y estimaba tanto,
no fueran lo que aparentaban ser.
Sin embargo, como yo deseaba fervientemente conocer la verdad,
sin importar lo que me costara, sentí el hacha puesta a la raíz del árbol,
y los hermosos edificios y las convincentes apariencias fueron conmovidas.
Me percaté, de que el árbol debía primero ser hecho bueno,
antes de que el fruto pudiera ser bueno.
Una doctrina esencialmente diferente de la que había oído de los hombres, incluso,
de los más estimados.
Pues se me había enseñado que la liberación del pecado
no debía ser esperada en esta vida,
y había escuchado día tras día,
la consistente confesión de que somos "`miserables pecadores,
carentes de salud espiritual,`" etc.

Encontré, por la manifestación de ese Espíritu que "`es dado a cada uno para provecho,`"^
footnote:[1 Corintios 12:7]
el Espíritu que pone al descubierto las cosas secretas de las tinieblas,
que esa confesión no era congruente, sino contraria a las Escrituras de verdad.
Porque estas expresamente declaran,
que el gran Autor de la dispensación del evangelio "`salvará a su pueblo __de__ sus pecados,`"^
footnote:[Mateo 1:21]
y no __en__ ellos--una diferencia fundamental.
Vi que esto debe ser conocido por experiencia,
al sentir el pecado como la gran enfermedad del alma
y única causa de separación del Altísimo,
el Único donde se halla la verdadera felicidad.
Fui consciente de que mientras permaneciera el pecado, la separación debía continuar,
ya que no había "`comunión entre la luz y las tinieblas,
ni entre la justicia y la injusticia;`"^
footnote:[2 Corintios 6:14]
ni podía ser cumplida la misericordiosa promesa, "`Habitaré y andaré entre ellos,
y seré su Dios, y ellos serán Mi pueblo,`"^
footnote:[2 Corintios 6:16]
pues el apóstol dice: "`Porque el templo de Dios, el cual sois vosotros, santo es.`"^
footnote:[1 Corintios 3:17]

¿Qué es un verdadero cristiano?
¿Es el que concuerda con ciertos hechos y cree en ellos,
como se registran en el escrito sagrado,
y que a partir de ahí forma ciertos principios y opiniones, realizando, tal vez,
una reforma parcial y absteniéndose de la más obvia contaminación del pecado,
pero negando la posibilidad de una total limpieza y libertad del pecado en este mundo?
¿O es aquel que no conoce sólo de palabra, sino de hecho y en verdad,
la muerte al pecado y el nuevo nacimiento para justicia, al nacer de nuevo no de sangre,
ni de voluntad de carne, ni de hombre, sino de Dios?
Porque nuestro bendito Señor dice: "`El que no naciere de nuevo,
no puede entrar al reino de Dios.`"^
footnote:[Juan 3:3]
Un hombre puede saber al igual que Nicodemo, y libremente confesar,
que Cristo es un maestro enviado por Dios;
puede ser capaz de hablar mucho acerca de las doctrinas
del evangelio e imaginarse a sí mismo seguro por imputación,
pero ¿qué tiene esto que ver con el nuevo nacimiento que es tan fundamentalmente necesario?
¿Qué le pueden enseñar toda su sabiduría y entendimiento?
No, el hombre no puede entrar al nuevo nacimiento hasta que haya renunciado a todo,
porque la naturaleza misma de la cosa implica un nuevo comienzo,
una vida tan esencialmente diferente de la anterior, como lo es la luz de las tinieblas.
"`Porque en otro tiempo erais tinieblas,`" dice Pablo,
"`mas ahora sois luz en el Señor.`"^
footnote:[Efesios 5:8]
Ahora bien, el que conoce este nuevo nacimiento--no un cambio de opinión,
ni una comprensión de las verdades del evangelio en su entendimiento,
o la unión a esta o aquella sociedad; el que conoce la cosa misma--no el nombre,
ni imaginaciones con respecto a ella, sino la naturaleza, la vida,
la esencia--¿permanecerá como era antes?

Cristo dijo: "`Bienaventurados los de limpio corazón,`"^
footnote:[Mateo 5:8]
pero los cristianos modernos dicen: "`No hay limpieza de corazón,
sino que es y debe permanecer engañoso más que todas las cosas y grandemente perverso.`"
Otra vez es dicho: "`¿Quién hará limpio a lo inmundo?`"^
footnote:[Job 14:4]
Ahora bien, es admitido que el corazón es impuro por naturaleza,
pero ¿no ha prometido el Señor limpiar a Su pueblo de "`toda su inmundicia`"?^
footnote:[Jeremías 33:8; Ezequiel 36:25]
Observe la palabra "`toda,`" ¿qué impureza permanecerá entonces?
Algunos intentan excusarse a sí mismos por lo que Pablo experimentó en algún momento,
"`Porque el deseo de la carne es contra el Espíritu,
y el del Espíritu es contra la carne,`"^
footnote:[Gálatas 5:17]
o "`pero veo otra ley en mis miembros, que se rebela contra la ley de mi mente.`"^
footnote:[Romanos 7:23]
Es reconocido que Pablo sintió esto alguna vez, pero ¿no dijo él después:
"`Ninguna condenación hay para los que están en Cristo Jesús,
los que no andan conforme a la carne, sino conforme al Espíritu`"^
footnote:[Romanos 8:1]? ¿Acaso no dijo:
"`La ley del Espíritu de vida en Cristo Jesús me ha librado de la ley del pecado,`"^
footnote:[Romanos 8:2]
y "`los que hemos muerto al pecado, ¿cómo viviremos aún en él?`"^
footnote:[Romanos 6:2]
¿Acaso no dice de nuevo: "`Con Cristo estoy juntamente crucificado,
y ya no vivo yo (no el yo natural ni pecaminoso), mas vive Cristo en mí`"^
footnote:[Gálatas 2:20]? "`Habitaré y andaré entre ellos.`"^
footnote:[2 Corintios 6:16]
¿Habitará el Señor en un lugar que no sea santo?
¿Puede la luz habitar con las tinieblas?

Ahora, Satanás puede disfrazarse, y de hecho lo hace, como ángel de luz.
Sí, se sienta como Dios, en el templo de Dios, haciéndose pasar por Dios.
La parte imaginativa en el hombre de seguro será engañada,
y adorará dicha aparición en lugar de la realidad,
porque el mundo mediante su sabiduría y el hombre mediante
sus habilidades naturales o humanamente adquiridas,
no conoció, ni podrá conocer a Dios jamás. Pero, "`si alguno,`" dice Pablo,
"`se cree sabio, hágase ignorante,`"^
footnote:[1 Corintios 3:18]
para que su ojo viejo sea cerrado y uno nuevo,
el único que puede discernir las cosas de Dios, sea abierto.
Cristo dice: "`Sed, pues, vosotros perfectos,
como vuestro Padre que está en los cielos es perfecto.`"^
footnote:[Mateo 5:48]
Pero los cristianos de hoy, como se llaman a sí mismos,
dicen que no hay tal cosa como la perfección. ¡Oh,
si pudieran considerar a quién se oponen diciendo esto!

¿Acaso no deseaba Pablo que aquellos a quienes les estaba escribiendo
se limpiaran "`de toda contaminación de carne y de espíritu,
perfeccionando la santidad en el temor de Dios`"^
footnote:[2 Corintios 7:1]? ¿No ora él que otros sean "`perfectos
y completos en todo lo que Dios quiere`"^
footnote:[Colosenses 4:12]? ¿No es lo que quiere decir este lenguaje claro y expreso?
¡Oh, la astucia de esa serpiente,
que es capaz de razonar y discutir el verdadero significado! ¡Oh,
el lamentable estado de los que están tan engañados por ella,
que están sentados cómodamente,
con la vana imaginación de que lo que Cristo ha hecho será suficiente,
sin necesidad de experimentar Su obra __en ellos!__ ¡Estos,
en el verdadero sentido espiritual, tienen ojos, pero no ven, oídos, pero no oyen!

Otra vez dice Cristo: "`No juréis en ninguna manera,`"^
footnote:[Mateo 5:34]
pero los cristianos de hoy dicen: "`Podemos jurar en algunos casos.
Razonaremos sobre las palabras de Cristo y juzgaremos por nosotros mismos qué significan,
y hasta qué punto deben ser obedecidas o no.`"
Aunque Santiago dice: "`Pero sobre todo, hermanos míos, no juréis,`"^
footnote:[Santiago 5:12]
aun así ustedes dicen: "`Podemos hacer tales y tales juramentos.`"
¡Oh, pobre cristiandad, cómo se ha ennegrecido tu oro!

Una vez más dice Cristo: "`Así, pues,
cualquiera de vosotros que no renuncia a todo lo que posee, no puede ser mi discípulo.`"^
footnote:[Lucas 14:33]
Pero ahora los cristianos pueden conservarlo todo--su propia sabiduría,
su propia voluntad, el favor del mundo, su riqueza y amistades, su moda y costumbres;
aunque Santiago diga: "`¿No sabéis que la amistad del mundo es enemistad contra Dios?`"^
footnote:[Santiago 4:4]
y Pablo diga, "`Pues si todavía agradara a los hombres, no sería siervo de Cristo.`"^
footnote:[Gálatas 1:10]

Además, Juan el Bautista, quien fue enviado para preparar el camino del Señor,
describiendo la naturaleza y efectos del reino de su Maestro dijo:
"`Y ya (note la palabra "`ya`") también el hacha está puesta a la raíz de los árboles;
por tanto, todo árbol que no da buen fruto es cortado y echado en el fuego.`"^
footnote:[Mateo 3:10]
¿A qué árbol y a qué raíz se hace referencia aquí? ¿Es externo o interno?
¿Quién puede responder esta pregunta,
sino aquel que ha sentido el hacha y la destrucción (en alguna medida) del árbol corrupto?
"`El aventador está en Su mano,`" y añade, "`y limpiará completamente Su era`"^
footnote:[Mateo 3:12; Lucas 3:17 (LBLA)]
(noten la palabra "`completamente`"). ¿Qué quedará entonces?
¡Oh, si los profesantes del cristianismo se interesaran por conocer,
y estuvieran dispuestos a desprenderse de todo lo que se interpone en
el camino! ¡Si pudieran realmente saber lo que es ser completamente limpiados,
en lugar de negar la posibilidad de ello! ¡Negarse
u oponerse al poder de Cristo es algo terrible!
Este es un lenguaje que ciertamente implica una limpieza
completa y efectiva de toda la contaminación del pecado,
incluso ya, en esta vida.

Nuestro Señor consistentemente inculcó esta doctrina en todos Sus discursos.
En el muy excelente '`Sermón del Monte,`' Él insiste en
la necesidad de una justicia superior a la de la ley,
pues dice:
"`Porque os digo que si vuestra justicia no fuere mayor que la de los escribas y fariseos,
no entraréis en el reino de los cielos.`"^
footnote:[Mateo 5:20]
¿Qué lenguaje puede ser más claro?
Y por lo que dice en la conclusión,
es evidente que Él no se refiere a una justicia imaginaria y meramente imputada,
como temo que muchos vanamente suponen,
porque hace una comparación entre los que oyen y __hacen__ sus dichos,
y los que oyen y no los hacen; estableciendo así plenamente, la posibilidad de hacerlos.

Si se presta la debida atención a cada parte de ese sermón,
creo que debe ser obvio que los que son el número feliz de los que no sólo oyen,
sino que también hacen esos dichos,
a quienes nuestro Señor asemeja a una casa edificada sobre la roca,
en la que son capaces de resistir toda oposición,
no son "`miserables pecadores que hacen lo que no deben hacer,
carentes de salud espiritual, etc.`"^
footnote:[Frases tomadas del [.book-title]#Libro de Oración Común#.]
Por el contrario, conocen una justicia obrada en ellos muy superior a la de la ley.
Porque tal como la ley, la ley externa, escrita en tablas de piedra,
habla de actos externos, así la ley de Cristo, escrita, como dice el apóstol,
en las tablas de carne del corazón, alcanza la raíz y origen del acto.
Porque mientras la ley decía: "`No matarás;`" Cristo prohíbe enojarse sin causa.
Y otra vez, mientras la ley decía: "`No cometerás adulterio,`" Cristo prohíbe la lujuria,
golpeando así la raíz. Al ser removida la causa,
la consecuencia o el efecto es inevitablemente eliminado.
Y una vez más, mientras la ley decía: "`Amarás a tu prójimo y aborrecerás a tu enemigo;
y ojo por ojo, y diente por diente,`" Cristo dice: "`No resistan al que es malo,
antes bien, amen a sus enemigos, hagan bien a los que los aborrecen.`"
Y dice mucho más con similar significado, a lo cual,
muchos que profesan seguirlo parece que le prestan
muy poca atención--como si hacerlo o no,
fuera un asunto sin importancia.
Pero puede que sea bueno para estos considerar si nuestro Señor hubiera dicho,
"`Sed pues perfectos,
como vuestro Padre que está en el cielo es perfecto,`"
si en realidad no quería que lo fueran.
Además, deben considerar si los que hacen lo que Él exhorta aquí,
no llegarán a ser perfectos.
No puedo concebir cómo es posible llegar a cualquier otra conclusión,
sin retorcer groseramente las Escrituras.

En otro momento dijo: "`Vosotros sois mis amigos, si hacéis lo que yo os mando.`"^
footnote:[Juan 15:14]
"`El que tiene mis mandamientos, y los guarda, ese es el que me ama.`"^
footnote:[Juan 14:21]
"`No todo el que me dice: Señor, Señor,
(que me llama Amo y me honra con sus labios) entrará en el reino de los cielos,
sino el que hace la voluntad de mi Padre que está en los cielos.`"^
footnote:[Mateo 7:21]
"`Si sabéis estas cosas, bienaventurados seréis si las hiciereis.`"^
footnote:[Juan 13:17]
Si una simple creencia en los sufrimientos, resurrección, etc.,
de Cristo es suficiente para salvar,
qué propósito tenían todos Sus discursos en los que
repetidamente insiste en la necesidad de regeneración,
o de nacer de nuevo, lo cual, ciertamente implica algo más que un cambio de opinión,
una persuasión del juicio y una reforma parcial.
Porque como Le dijo a Nicodemo: "`Lo que es nacido de la carne, carne es;
y lo que es nacido del Espíritu, espíritu es.`"^
footnote:[Juan 3:6]
De esto obviamente se deduce, que los que realmente nacen del Espíritu,
serán de la misma naturaleza del Espíritu.
Todas las cosas viejas pasarán, todas serán hechas nuevas y todo provendrá de Dios.
"`Un poco de levadura leuda toda la masa.`"^
footnote:[1 Corintios 5:6]
"`El vino nuevo en odres nuevos se ha de echar.`"^
footnote:[Marcos 2:22]
Y muchas otras comparaciones,
de las que claramente se implica la necesidad de un cambio total y efectivo.

Nuevamente, para confirmar esta grande y necesaria verdad de la libertad del pecado,
Él les dice a Sus discípulos: "`Si vosotros permaneciereis en mi palabra,
seréis verdaderamente mis discípulos; y conoceréis la verdad,
y la verdad os hará libres.`"^
footnote:[Juan 8:31]
Y para reprender sus ideas carnales de una libertad temporal y externa, añade:
"`Todo aquel que hace pecado, esclavo es del pecado, así que, si el Hijo os libertare,
seréis verdaderamente libres.`"^
footnote:[Juan 8:34 y 36]
Que esta libertad del pecado, es decir, del poder del pecado,
así como también de la culpa, debe ser experimentada en esta vida,
queda de nuevo confirmada por lo que dice de los que mueren en sus pecados:
"`A donde yo voy, vosotros no podéis venir.`"^
footnote:[Juan 8:21]
Ahora, si no se experimenta la liberación del pecado en esta vida,
necesariamente se muere en los pecados, sin importar qué conocimiento tenga el hombre,
cuál sea su fe o qué profesión haya practicado.
Este punto es muy importante, y un error en él puede tener consecuencias muy dañinas.
Por tanto, me veo obligado a detenerme en ello, sabiendo por experiencia propia,
cuán predominante es la opinión contraria.

En realidad,
no es difícil entender por qué las personas prefieren
ser libres de __la culpa y del castigo__ del pecado,
sin que el __poder__ del pecado sea sometido: Porque naturalmente amamos la facilidad;
la facilidad a la que la cruz de Cristo se opone decididamente.
La aplicación de la cruz es tan rigorosa, que es, en las propias palabras del Señor,
como amputar la mano derecha y sacar el ojo derecho.^
footnote:[Mateo 6:29-30]
Él dice una y otra vez, "`El que no lleva su cruz y viene en pos de mí,
no puede ser mi discípulo.`"^
footnote:[Lucas 14:27]
El apóstol da testimonio de esta importante verdad, donde dice:
"`Los que son de Cristo han crucificado la carne con sus pasiones y deseos.`"^
footnote:[Gálatas 5:24]
Si las pasiones y deseos--la raíz y semilla mismas del pecado--son ciertamente asesinados,
¿qué puede quedar?
En otro lugar él dice: "`Porque los que hemos muerto al pecado,
¿cómo viviremos aún en él?`"^
footnote:[Romanos 6:2]
Y otro apóstol dice: "`Todo aquel que es nacido de Dios, no practica el pecado,
porque la simiente de Dios permanece en él; y no puede pecar,
porque es nacido de Dios.`"^
footnote:[1 Juan 3:9]

He presentado unos pocos y sencillos pasajes de las Escrituras,
para mostrar que la liberación del pecado--al ser limpiados de
toda contaminación del pecado en esta vida--no sólo es posible,
sino indispensablemente necesaria,
y que la doctrina contraria es fundamentalmente errónea,
ya que establece la sombra en lugar de la sustancia,
y una santidad imaginaria en lugar de la real.
Probablemente haga más observaciones de este punto tan importante conforme avance.

Ahora ofreceré unas pocas observaciones
de algunos de los servicios religiosos que se realizan usualmente,
comparándolos también con las Escrituras de verdad (las cuales,
la mayoría de los profesantes cristianos reconocen como su estándar o regla),
comparación que mostrará claramente, creo,
que estos servicios no son lo que muchos llaman "`medios
de gracia`" y "`ordenanzas de Dios.`"
Más bien parecen ser meras invenciones de los hombres,
establecidas en su propia sabiduría caída,
como sustitutos de la vida y del poder que se perdieron en la larga noche de la apostasía,
al no ser la verdadera adoración de Dios,
sino ejercicio corporal que "`para poco es provechoso,`"^
footnote:[1 Timoteo 4:8]
como dice el apóstol.
Porque recordemos que el gran Autor de la dispensación del evangelio expresamente declaró,
que "`los verdaderos adoradores adorarán al Padre en espíritu y en verdad.`"^
footnote:[Juan 4:23]
Y el apóstol confirma esto diciendo: "`Pues qué hemos de pedir como conviene,
no lo sabemos, pero el Espíritu mismo intercede por nosotros con gemidos indecibles.`"^
footnote:[Romanos 8:26]

Por lo tanto,
al ver que esta necesaria asistencia no está a nuestras órdenes,
se deduce que pretender adorar al Altísimo en una forma prescrita,
o con creaciones estudiadas o improvisadas de las
habilidades propias o adquiridas del hombre,
en su propia voluntad y tiempo,
sin esperar sentir las influencias y movimientos del Espíritu Santo (en
y a través del cual únicamente se puede realizar la verdadera adoración),
no puede ser mejor que el "`culto voluntario,`" sin importar cómo sea llamado.^
footnote:[El término "`culto voluntario`" viene de Colosenses 2:23,
donde Pablo habla de las "`cosas que tienen a la verdad
cierta reputación de sabiduría en culto voluntario,
en humildad y en duro trato del cuerpo, etc.`"
El término es usado para describir la adoración que es según la propia imaginación,
simplemente impuesta por la voluntad humana, y no por la autoridad o asistencia divina.]

Las Escrituras también hablan repetidamente, de crecer en la gracia,^
footnote:[2 Pedro 3:18]
de continuar hacia la perfección.^
footnote:[Hebreos 6:1]
¿Cuán incompatible es entonces, la repetida e inalterada confesión:
"`Nosotros somos pecadores miserables,
que hacemos lo que no debemos,`" etc.? ¿No es esta confesión, si se dijera la verdad,
una obvia manifestación de que no se ha recibido ningún beneficio a pesar
de la frecuente (como se afirma) búsqueda del Señor? Pero si es cierto,
como lo declaran las Escrituras,
que Cristo vino para salvar "`a su pueblo de sus pecados,`"^
footnote:[Mateo 1:21]
entonces los que hacen tal confesión, admiten que no son de dicho número.
Pues si todavía son pecadores miserables, claramente no son salvos de sus pecados,
por más que intenten reconciliar una contradicción tan clara.

Esta incompatibilidad no está limitada a una parte en particular del servicio,
porque su presencia en la totalidad es igualmente obvia.
Porque en un momento,
se escuchan a las personas confesando sus propios pecados y maldades,
y poco después son llamadas a dirigirse al Altísimo con corazones puros, humildes,
penitentes y obedientes.
En un momento admiten haber errado y haberse extraviado como ovejas perdidas,
pero luego declaran que mostrarán su alabanza no sólo con sus labios, sino con sus vidas,
rindiéndose al servicio del Señor y caminando delante de Él en santidad
y justicia todos sus días (aunque sigan siendo miserables pecadores,
haciendo lo que no deben hacer, etc.). ¿Puede este correr para atrás y para adelante,
que en un momento se dice una cosa y en otro todo lo contrario,
ser un servicio aceptable para el Dios que escudriña el corazón,
prueba la mente y requiere la verdad en lo íntimo?
Y cuando todos repiten en voz alta las experiencias del salmista real,
¿es posible evitar que se pronuncien muchas obvias falsedades?
Pues si las palabras de la boca no son la expresión del
lenguaje real y conocido por experiencia del corazón,
por muy excelentes que sean, no son palabras que brotan de la verdad,
sino palabras falsas en la boca de los que las pronuncian.
¡Espero que un poco de consideración seria convenza de esto!

Ahora, con respecto a la costumbre o práctica de cantar,
tengo algunas observaciones que hacer.
¿Acaso no es contradictorio que los que justo antes han confesado su miseria y desdicha,
parezcan olvidar todo eso rápida y fácilmente, e inmediatamente empiecen a cantar?
Esto parece una evidente declaración de que no fueron sinceros en lo que reconocieron,
o de que creen que es de muy poca importancia si sus oraciones son respondidas o no.
¿No es esto jugar con cosas serias?
Estoy completamente persuadido de que la práctica común
de cantar sólo se calcula para divertir a la criatura,
para agradar el oído externo,
por mucho que se afirme que calienta el corazón y enciende la devoción.
Y si los que lo practican fueran honestos y sinceros,
soy de la opinión de que serían constreñidos a reconocer que en realidad,
el entretenimiento es el objetivo principal; de lo contrario,
¿por qué están tan complacidos con las melodías y la música?
¿Se puede suponer por un momento que el Todopoderoso
debe ser honrado por una conducta tan superficial?
Definitivamente no.
Y con respecto a la devoción encendida,
puede ser bueno que se recuerde lo que les fue dicho
a los que '`encienden un fuego y se rodean de teas;
puede que anden a la luz de ese fuego, pero en dolor serán sepultados.`'^
footnote:[Isaías 50:11]

Soy consciente de que hay Escrituras que se usan para defender esta costumbre:
Que nuestro Señor y Sus discípulos, la noche antes de que Él sufriera, cantaron un himno;
pero qué o cómo, no estamos informados.
No me cabe la menor duda,
de que el asunto y la manera fueron tanto apropiados como oportunos.
Que el apóstol Pablo y Silas cantaron alabanzas al Señor en prisión,
por supuesto que lo creo, pero no puedo concebir qué argumento pueda deducirse de esto,
que justifique la presente costumbre de cantar cualquier
cosa que se escoja para el servicio,
adecuado o no--ya sea alabanza, profesión,
reconocimiento o petición. Encuentro que este canto externo y escogido
de antemano es muy diferente de ese que recomendó el apóstol:
"`Cantaré con el espíritu, pero cantaré también con el entendimiento,`"^
footnote:[1 Corintios 14:15]
o, "`cantando y alabando al Señor en vuestros corazones.`"^
footnote:[Efesios 5:19]
También creo que la fuente verdadera de alabanza--es decir,
el sentido agradecido por las misericordias del Señor--puede
expresarse mejor y más apropiadamente,
que en un tintineo y sonido externo.

Siempre se debe tener en cuenta que Dios es Espíritu y que los que lo adoran,
deben adorarlo en Espíritu y en verdad.
En otras palabras, Él considera el lenguaje del corazón, no las palabras,
por muy excelentes que sean.
Ahora invoco al Testigo de Dios en cada corazón,
para la consideración de la siguiente pregunta:
En vista de la variedad de condiciones de los presentes en una reunión,
y del distinto tema de cada canción--sea de alabanza, adoración, confesión, petición,
etc.--¿es probable que la congregación, con propiedad y en el temor del Señor,
en cualquier estado o condición en que se encuentre en el momento,
esté correctamente preparada para cantar lo que sea que se le dé? A mí me parece
imposible que toda una congregación esté en el mismo estado de ánimo,
considerando los diferentes tratos de la providencia del Señor con Su pueblo.
En consecuencia, obviamente se deduce, que si todos cantan,
algunos pronuncian palabras con la boca muy contrarias al lenguaje del corazón,
lo cual está tan lejos de ser aceptable para el Señor,
que estoy persuadido de que es hipocresía y una abominación ante Sus ojos.

Ahora,
hablándoles más específicamente a los que han alcanzado una medida de gracia de Dios,
pregúntense seriamente:
¿El canto externo está destinado o calculado para agradar
los oídos carnales de los hombres o al Dios santo?
¿Por qué tanta ansiedad sobre las melodías, voces y música?
¿Debe agradarse el Señor con esas cosas terrenales?
¡Oh no, ustedes no pueden suponer esto!
Consideren de cuál raíz brotan, del viejo o del nuevo hombre;
y recuerden que Su hacha está puesta a la raíz para destruir todo lo que es de la tierra,
de nuestra naturaleza carnal.

He considerado esos pasajes en el Nuevo Testamento donde el tema es mencionado,
y siento que confirman mi opinión en cuanto a la incompatibilidad del canto público.
El apóstol habla de cantar con gracia en el corazón,
de hacer melodías en el corazón para el Señor,
no de hacer sonidos con la boca a menos que procedan del corazón;
sobre lo cual,
llamo a que todas las mentes serias consideren,
cuán raramente ocurre esto en el canto público.

Estoy convencido en mi propia mente, considerando nuestra situación aquí,
el poder y las artimañas del enemigo y nuestras propias corrupciones innatas,
que sería más apropiado vigilar y orar, y estar siempre en guardia,
esperando sentir la luz y poder de Cristo develar
y subyugar las cosas ocultas de las tinieblas,
que manifestar ese espíritu desenfadado y descuidado,
que con demasiada frecuencia acompaña el canto público.
Entonces, como hijos de la luz,
podríamos caminar en la luz y experimentar la sangre de Jesucristo, Su Espíritu y poder,
limpiándonos de todo pecado.

Díganme, ¿cómo pueden esos que están presentes,
que viven en abierta y declarada oposición a Dios,
unirse en canto sin pronunciar mentiras obvias y abominables?
¿Acaso no somos cómplices de esto?
¿Acaso no se espera que cuando se anuncia un salmo o himno todos los presentes canten?
Que no se diga entonces: "`¿Cómo podemos evitar el abuso de esto?`"
¿No deberíamos más bien darles un ejemplo de verdad y justicia,
y no aprobar ninguna práctica que tenga la tendencia de promover la ligereza y la irreverencia?
¡Oh, mis amigos, esto no puede ser aceptable para el Señor,
quien requiere la verdad en lo íntimo!
Recomiendo que consideren seriamente lo que el Señor dice en el primer
capítulo de Isaías con respecto a las ordenanzas que Él mismo designó,
cuando no son hechas en el espíritu apropiado: "`¿Para qué me sirve, dice Jehová,
la multitud de vuestros sacrificios?
Hastiado estoy de holocaustos de carneros y de sebo de animales gordos;
no quiero sangre de bueyes, ni de ovejas, ni de machos cabríos,`"^
footnote:[Isaías 1:11] etc.

Percibo día a día, una cada vez más evidente salida de la sencillez de Cristo.
¿Dónde es llevada la cruz cada día? Observen la apariencia de los profesantes del cristianismo.
¿Qué diferencia hay con el mundo?
Mis amigos, estas cosas no deben ser.
¡Ténganme paciencia, se los ruego!
Estoy muy interesado por el honor de nuestra profesión.
Si la cruz es verdaderamente llevada,
se elimina todo egoísmo y autocomplacencia,
y se evidencian más los frutos del Espíritu en la seriedad
y solemnidad de la verdadera profesión cristiana.
¡Qué el Señor haga que estas cosas calen cada corazón,
para que se experimente la necesidad de ofrecerle un sacrificio aceptable,
del cual se dice en más de una ocasión, que es un espíritu contrito y humillado!

'`Bienaventurados ustedes los que lloran, porque se regocijarán,`' dice Cristo.
Entiendo este '`regocijar,`' como el resultado de una consciencia
agradecida por la experiencia de las misericordias del Señor,
y como una manifestación de alabanzas a Él,
no sólo con nuestros labios sino con nuestras vidas.
¡Oh, amigos míos, vuélvanse hacia sus propios corazones.
"`He aquí,`" dice Cristo, "`el reino de Dios dentro de vosotros está.`"^
footnote:[Lucas 17:21, RV1602P]
No busquen fuera lo que estoy convencido que únicamente se encuentra dentro.
No es el mucho oír o el mucho hablar lo que trae verdadera paz al alma,
porque el oído nunca se satisface de oír. ¿No vemos profesantes
del cristianismo corriendo de aquí para allá,
creyendo que cuánto más oigan, mejores serán,
y rodeándose de las teas que ellos mismos encendieron?
Pero, ¿qué les dice el Señor? "`En dolor seréis sepultados.`"^
footnote:[Isaías 50:11]
Estoy completamente convencido,
de que por falta de mirar hacia el interior y no esperar sentir
el poder del Señor ahí (juzgando y sometiendo el pecado),
hay tanta charla, tanto espectáculo externo,
pero lo espiritual está casi ausente en las vidas y conversaciones de las personas.

¡Ay, mis amigos, me temo que muchos de ustedes (en conformidad con su propia profesión),
están en una condición miserable!
Ahora, permítanme convencerlos de que consideren,
si el hecho de que año tras año continúen siendo miserables pecadores,
no es consecuencia de que sus oraciones no están siendo contestadas.
Dejen que se levante una inquietud y pregúntense,
si han estado buscando correctamente o no,
porque nuestro Señor prometió clara y expresamente, "`que todo el que busca, halla.`"^
footnote:[Mateo 7:8]
Ahora,
¿qué han encontrado los que continúan (como ellos admiten) siendo "`miserables pecadores,
haciendo lo que no deben hacer,
etc.`"? ¿No es esta una confesión de que los medios que
han usado son insuficientes para limpiarlos y sanarlos;
que no han acudido correctamente al Gran Médico, al bálsamo de Galaad,
a "`las hojas del árbol +++[+++que]
son para la sanidad de las naciones;`"^
footnote:[Apocalipsis 22:2]
sino que han estado "`gastando el dinero en lo que no es pan,
y su trabajo en lo que no sacia,`" en lugar de "`oír
atentamente al Señor y comer del bien,`"^
footnote:[Isaías 55:2]
el verdadero pan de vida, del que nuestro Señor dijo: "`el que come de este pan,
vivirá eternamente`"^
footnote:[Juan 6:58]? Sería bueno que busquen estos medios,
antes de que la posibilidad de una cura sea negada;
no sea que nieguen que el poder de Dios es capaz de '`expulsar al hombre fuerte,
quien guarda su palacio y sus bienes en paz.`'^
footnote:[Lucas 11:21]
El apóstol habla de algunos, "`que tienen apariencia de piedad,
pero han negado su poder.`"^
footnote:[2 Timoteo 3:5 LBLA]
Ahora, sería bueno que consideren, en qué se puede conocer el poder de la piedad,
sino en el dominio sobre su adversario, el cual es el pecado.
Los que niegan la posibilidad de que el pecado puede ser sometido,
¿acaso no niegan el poder de la piedad?

A menudo me he preguntado,
cómo es posible que aquellos que abogan por la necesidad de pecar,
pueden afirmar también el valor de las Escrituras, diciendo:
"`¡Las Escrituras son la regla!`"
Porque las Escrituras insisten, consistentemente, en la necesidad de santidad;
no una santidad imaginaria, sino una pureza real de corazón y de vida.
"`Sin santidad,`" dijo el apóstol, "`nadie verá a Dios.`"^
footnote:[Hebreos 12:14]
"`Como aquel que os llamó es santo,
sed también vosotros santos en toda vuestra manera de vivir.`"^
footnote:[1 Pedro 1:15]
"`Os ruego por las misericordias de Dios,
que presentéis vuestros cuerpos +++[+++noten que dice "`cuerpos`"]
en sacrificio vivo, santo, agradable a Dios, que es vuestro culto racional.`"^
footnote:[Romanos 12:1]
Los profesantes cristianos hablan mucho de la sangre de Cristo;
es un tema frecuente en sus bocas,
pero cuánto han experimentado de la naturaleza y efectos de esta;
¡qué sus propias confesiones testifiquen!
El apóstol declara que "`la sangre de Jesucristo su Hijo nos limpia de todo pecado.`"^
footnote:[1 Juan 1:7]
Ahora, cómo pueden estar limpios de todo pecado,
los que continúan siendo "`miserables pecadores, haciendo lo que no deben hacer,
etc.;`" lo dejo a la consideración de la mente que discierne.

Me propongo ahora, responder algunas objeciones a esta importante verdad,
y comentar algunos pasajes de las Escrituras, con los que,
los que niegan la posibilidad de que el pecado puede ser sometido,
hacen el esfuerzo por cubrirse.

La primera objeción tiene que ver con la Escritura que dice:
"`Engañoso es el corazón más que todas las cosas, y perverso; ¿quién lo conocerá?`"^
footnote:[Jeremías 17:9]
Creo firmemente que el corazón de todo hombre, o de todo hombre natural no regenerado,
es verdaderamente así. Pero debe ser recordado que el Señor le prometió a Su pueblo:
"`Os daré corazón nuevo, y pondré espíritu nuevo dentro de vosotros.`"^
footnote:[Ezequiel 36:26]
¿Se atreve alguien a decir que __ese__ corazón es engañoso y perverso?
¡Oh, cuidado con despreciar el don de Dios! "`Bienaventurados los de limpio corazón,
porque ellos verán a Dios,`"^
footnote:[Mateo 5:8]
dice nuestro Señor. "`No puede el buen árbol dar malos frutos,
ni el árbol malo dar frutos buenos.`"^
footnote:[Mateo 7:18]
"`Mas la que cayó en buena tierra,
éstos son los que con corazón bueno y recto retienen la palabra oída,
y dan fruto con perseverancia.`"^
footnote:[Lucas 8:15]
Porque ahora, en la dispensación del evangelio,
"`el hacha está puesta a la raíz del árbol.`"^
footnote:[Mateo 3:10]
¿Qué es la raíz del árbol sino el corazón, del que nacen todas las palabras y actos?
Cristo dijo: "`¡Fariseo ciego!
Limpia primero lo de dentro del vaso y del plato,
para que también lo de fuera sea limpio.`"^
footnote:[Mateo 23:26]
En sus oraciones escritas,
¿no le piden a Dios que limpie los pensamientos de sus corazones,
por la inspiración de Su Santo Espíritu?
¡Una muy excelente petición! Pero, ¿de qué sirve esa petición para los que la hacen,
cuando niegan la posibilidad de que sea respondida?
¿No es una solemne burla?
Porque si los pensamientos del corazón están en realidad limpios, no debe haber pecado;
pues el pecado mancha y contamina el corazón.

Otra objeción es el lenguaje que usa el apóstol donde habla de la "`ley en mis miembros,
que se rebela contra la ley de mi mente, y que me lleva cautivo a la ley del pecado,`"^
footnote:[Romanos 7:23]
y "`yo sé que en mí, esto es, en mi carne, no mora el bien.`"^
footnote:[Romanos 7:18]
Creo que está fuera de toda duda, que el apóstol alguna vez estuvo en ese estado,
y que ciertamente,
todo cristiano verdadero experimenta un estado similar hasta
que el hombre fuerte es echado y la vieja levadura purgada.
Pero que Pablo estaba en dicho estado en el momento de escribir su epístola,
no me parece por ningún medio creíble por lo que
escribió antes y por lo que escribió después,
o de lo contrario, obviamente se habría contradicho, lo cual difícilmente se puede creer.
Él, sin ninguna duda,
estaba describiendo aquí los efectos de la ley sobre la mente carnal no regenerada,
porque dice: "`La ley es espiritual; mas yo soy carnal, vendido al pecado.`"^
footnote:[Romanos 7:14]
¿Se puede suponer que el apóstol todavía era carnal?
Ciertamente no, tras haber dicho:
"`La mente carnal es enemistad contra Dios,`" y "`la mente carnal es muerte,`" y "`los
que están en la carne no pueden agradar a Dios,`" y "`mas vosotros no estáis en la carne,
sino en el Espíritu: si es que el Espíritu de Dios mora en vosotros.
Y si alguno no tiene el Espíritu de Cristo, el tal no es de él.`"^
footnote:[Romanos 8:6-9, RV1602P]
En consecuencia se deduce, que si el apóstol estaba entonces en el estado carnal,
no era de Cristo, sino que estaba en "`enemistad contra Dios.`"
Pero un poco antes había dicho: "`Sabiendo esto,
que nuestro viejo hombre es crucificado con él,
para que el cuerpo del pecado sea destruido, a fin de que no sirvamos más al pecado.
Porque el que está muerto, libre es del pecado.`"^
footnote:[Romanos 6:6-7, RV1602P]
Y, "`mas ahora librados del pecado, y hechos siervos de Dios,
tenéis por vuestro fruto la santidad, y por fin la vida eterna.`"^
footnote:[Romanos 6:22]
Entonces, que este sencillo lenguaje, escrito tanto antes como después de Romanos 7,
y sin ninguna duda en la misma ocasión,
determine si el apóstol estaba o no en ese momento, en un estado carnal y no regenerado.

Y aunque él dice en otra parte, "`no que lo haya alcanzado ya, ni que ya sea perfecto,`"^
footnote:[Filipenses 3:12]
creo que esto en ningún sentido favorece la interpretación que muchos ponen sobre esto,
queriendo implicar que el apóstol estaba en ese momento en un estado pecaminoso.
Más bien, esta Escritura parece obrar contra ellos,
ya que condena claramente la idea de que pueden ser justificados
perfectamente y para siempre por una mera imputación,
y evidencia el peligro de sentarse a gusto,
descansando satisfechos con una justificación imaginaria.
Pues en otro lugar, hablando del progreso cristiano,
Pablo declara que él no corría '`como a la ventura,`' ni peleaba
'`como alguien que golpea al aire,`' más bien encontró que era
necesario mantener su cuerpo humillado y llevarlo a servidumbre,
o corría el peligro de ser eliminado, a pesar de que les había predicado a otros.^
footnote:[1 Corintios 9:26-27]

Otra objeción contra la necesidad de experimentar la liberación del pecado,
es tomada de las palabras del mismo apóstol donde dice:
"`Porque por gracia sois salvos por medio de la fe; y esto no de vosotros,
pues es don de Dios; no por obras, para que nadie se gloríe.`"^
footnote:[Efesios 2:8-9]
En respuesta a la cual, creo que es muy necesario distinguir entre las obras del hombre,
que él hace en su propia voluntad y fuerza,
y las obras que son preparadas de antemano por Dios.
Tal vez es por no conocer correctamente esta diferencia,
que las personas exclaman contra las obras,
como si todas ellas fueran resultado de la justicia propia.
En efecto, las obras del hombre, de la mente carnal no renovada, sí,
incluso las mejores de ellas, son como trapos de inmundicia.
Pero creo que se debe tener gran cuidado de no unir
las obras de Dios (esas que Él obra en Su pueblo),
con las propias obras del hombre, porque en el siguiente versículo dice el apóstol:
"`Porque somos hechura suya, creados en Cristo Jesús para buenas obras,
las cuales Dios preparó de antemano para que anduviésemos en ellas.`"^
footnote:[Efesios 2:10]
Que esto es por gracia, creo que ningún cristiano verdadero lo negará,
sino que con humilde gratitud en todo su progreso, reconocerá con el apóstol:
"`Por la gracia de Dios soy lo que soy.`"^
footnote:[1 Corintios 15:10]
Esta es la misma gracia que el apóstol declara,
"`se ha manifestado&hellip;a todos los hombres +++[+++noten que no
dice '`a una parte específica`' de los hombres],
enseñándonos que, renunciando a la impiedad y a los deseos mundanos,
vivamos en este siglo sobria, justa y piadosamente.`"^
footnote:[Tito 2:11-12]
Él no dice que la gracia enseña que debemos continuar en pecado.
"`¿Qué?,`" dice en otro lugar,
"`¿Perseveraremos en el pecado para que la gracia abunde?`"^
footnote:[Romanos 6:1]
Y que esto es también por fe,
¿quién lo negará? Porque "`sin fe es imposible agradar a Dios.`"^
footnote:[Hebreos 11:6]
Pero el apóstol habla de una fe muerta,^
footnote:[Santiago 2:17]
de una fe que tienen los demonios,^
footnote:[Santiago 2:19]
y de una fe verdadera, de la que se dice, "`obra por el amor,`"^
footnote:[Gálatas 5:6]
purifica los corazones^
footnote:[Hechos 15:9]
y vence al mundo.^
footnote:[1 Juan 5:4]
Entonces,
cuál fe tienen los que dicen que están "`atados y encadenados con la cadena de sus pecados,
que son miserables pecadores sin salud espiritual en ellos,`" etc.
El árbol es conocido por sus frutos.

He escuchado las palabras de nuestro Señor a los que sanó de enfermedades:
"`Tu fe te ha salvado,`" "`tu fe te ha hecho salva,`"^
footnote:[Mateo 9:22; Marcos 5:34, 10:52; Lucas 7:50; 8:48; etc.]
etc.,
alegadas como una excusa para continuar en pecado
siempre y cuando tengamos una medida de fe.
Pero recordemos que aquellos a quienes el Señor les dijo estas palabras,
fueron completamente curados al recibir "`completa sanidad;`"^
footnote:[Hechos 3:16]
y creo, que hay un remanente hoy,
que experimenta las mismas obras cumplidas espiritualmente por
la poderosa operación de la misma Palabra en sus corazones;
es decir, ser hechos completos, ser sanados de la gran enfermedad del pecado,
lo cual fue prefigurado por las muchas sanidades realizadas en los cuerpos de las personas.

Un argumento más comúnmente alegado, es lo dicho por el apóstol:
"`Si decimos que no tenemos pecado, nos engañamos a nosotros mismos,
y la verdad no está en nosotros.`"^
footnote:[1 Juan 1:8]
Pero una debida atención a lo que sigue no favorece la idea
de que él estaba entonces en ese estado pecaminoso,
porque añade: "`Si decimos que no hemos pecado,`"^
footnote:[1 Juan 1:10]
claramente aludiendo al tiempo pasado, y continúa: "`Si confesamos nuestros pecados,
él es fiel y justo para perdonar nuestros pecados, y limpiarnos de toda maldad.`"^
footnote:[1 Juan 1:9]
Sabiendo que "`toda injusticia es pecado,`"^
footnote:[1 Juan 5:17]
los que están limpios de todo, ciertamente no pueden tener nada restante.
El mismo apóstol habla fuertemente a favor de esta perfecta limpieza donde afirma:
"`Todo aquel que permanece en él, no peca;`" "`para esto apareció el Hijo de Dios,
para deshacer las obras del diablo;`" "`todo aquel que es nacido de Dios,
no practica el pecado, porque la simiente de Dios permanece en él; y no puede pecar,
porque es nacido de Dios.`"^
footnote:[1 Juan 3:6, 8, 9]

Es el sincero deseo de mi alma, que las personas consideren por sí mismas,
y que no asuman entender cosas de tal importancia de oídas.
Sino que todas atiendan el consejo del apóstol:
"`Cada uno someta a prueba su propia obra,
y entonces tendrá motivo de gloriarse sólo respecto de sí mismo, y no en otro;
porque cada uno llevará su propia carga.`"^
footnote:[Gálatas 6:4-5]
Y agrega justo después: "`No os engañéis; Dios no puede ser burlado:
pues todo lo que el hombre sembrare, eso también segará,`"^
footnote:[Gálatas 6:7]
cualquiera que sea su opinión, conocimiento o fe.
En otro lugar él dice, que aunque un hombre tenga todo el conocimiento,
entienda todos los misterios y tenga toda la fe, incluso para mover montañas,
aun así no podría ser nada.^
footnote:[1 Corintios 13:2]

Por lo tanto, sería prudente tener cuidado de insistir en la autoridad de las Escrituras,
mientras que la vida y la conducta no son acordes con ellas.
Recuerden las palabras de nuestro Señor a algunos de los antiguos:
"`Ustedes examinan las Escrituras porque piensan tener en ellas la vida eterna.
¡Y son ellas las que dan testimonio de Mí! Pero ustedes
no quieren venir a Mí para que tengan esa vida.`"^
footnote:[Juan 5:39-40, NBLH]
De esto se desprende, y es digno de la más seria atención,
que los que tenían las Escrituras y las valoraban (tanto
como para pensar que tenían vida eterna en ellas),
no iban a Cristo, de quien ellas testificaban, el Único que era y es,
tanto la vida como la luz de los hombres.^
footnote:[Juan 1:4]
Por esta razón, sería bueno tener cuidado de poner la letra, el testimonio,
la declaración con respecto a un objeto, en el lugar del objeto mismo,
porque nuestro Señor no dijo que las Escrituras fueran el camino,
sino "`Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.`"^
footnote:[Juan 14:6]
De hecho, nosotros debemos aprender la diferencia entre la letra, la palabra externa,
y la Palabra que estaba en el principio,^
footnote:[Juan 1:1]
antes de las Escrituras, es decir, "`la palabra +++[+++cerca], en tu boca y en tu corazón,`"^
footnote:[Romanos 10:8]
la cual es "`viva y eficaz, y más cortante que toda espada de dos filos,
y penetra hasta partir el alma y el espíritu, las coyunturas y los tuétanos,
y discierne los pensamientos y las intenciones del corazón&hellip;antes bien todas las cosas
están desnudas y abiertas a los ojos de aquel a quien tenemos que dar cuenta.`"^
footnote:[Hebreos 4:12-13]
De Él, tal como mencioné antes, testifican las Escrituras, y sin Su todopoderosa ayuda,
estas permanecen como letra muerta y un libro sellado.
El apóstol declaró que las cosas de Dios sólo pueden
ser conocidas por medio del Espíritu de Dios.^
footnote:[1 Corintios 2:11]
Ellas son locura para el hombre natural.
Por tanto,
creo que debemos tener cuidado en la manera de como intentamos comprender las verdades
que están contenidas en las Escrituras mediante nuestro propio entendimiento;
más bien debemos estar dispuestos, como recomienda el apóstol, a hacernos "`ignorantes,
para que lleguemos a ser sabios.`"^
footnote:[1 Corintios 3:18]

Ahora quiero ofrecer unas observaciones sobre esas dos ordenanzas o ceremonias:
El bautismo y la cena del Señor, tal como se les llama.

Con respecto al bautismo,
tal como es practicado por aquellos a quienes me dirijo más específicamente,
se necesita decir poco,
pues rociar a los infantes ni siquiera es una imitación del verdadero bautismo.
No tiene ninguna relación con este,
ni creo que pueda encontrarse un solo precepto o
ejemplo de esto en las Escrituras de verdad.
Estoy completamente convencido de que es, como muchas otras cosas de ese tipo,
una invención católica de los tiempos de oscuridad y apostasía,
como un sustituto de la realidad,
porque en ningún sentido está calculado para responder a algún buen propósito.
Puede que sea bueno considerar seriamente el lenguaje que se usa durante esa ceremonia,
en la que se dice:
"`Este niño es regenerado e injertado en el cuerpo de la iglesia de Cristo.`"
En el catecismo se dice con respecto a este, que el niño en el bautismo,
"`es hecho miembro de Cristo, un hijo de Dios, y un heredero del reino de los cielos.`"
Que cada persona sensata solemnemente se pregunte,
si realmente cree que esa ordenanza produzca tales efectos.
Si es posible que alguien piense así,
sus ideas de la regeneración y de la iglesia de Cristo difieren ampliamente de la mías.

Consideremos también lo que se les enseña a las personas a prometer en esta ceremonia:
'`A renunciar al diablo y a todas sus obras,
a la pompa y vanidades de este mundo maligno,
y a todos los deseos pecaminosos de la carne,
para guardar la voluntad y mandamientos santos de Dios y caminar en estos,
todos los días de sus vidas.`' ¿Acaso no se les
obliga aquí a prometer lo que creen y confiesan que es imposible hacer?
Porque si eso fuera cumplido, de seguro no serían "`miserables pecadores,
que hacen lo que no deben hacer, etc.`"

Ahora, yo plenamente creo, que el bautismo es necesario,
absolutamente necesario para cada miembro de la iglesia de Cristo,
pero no creo que la aplicación de agua, aun cuando sea correctamente imitada,
sea el único verdadero bautismo mencionado en las Escrituras.^
footnote:[Efesios 4:5]
Porque no es la eliminación de la inmundicia de la carne (lo cual
es todo lo que el agua externa y natural puede hacer),
sino ser bautizados en "`el bautismo del Espíritu Santo y fuego,`"^
footnote:[Mateo 3:11]
es decir, ser bautizados en el __Nombre__ (que es la naturaleza) del Padre,
Hijo y Espíritu Santo,
y de este modo experimentar la eliminación de la parte terrenal en nosotros,
y ser limpiados y purificados de toda inmundicia de carne y espíritu,
perfeccionando la santidad en el temor del Señor.^
footnote:[2 Corintios 7:1]
Porque el apóstol dice: "`Porque todos los que habéis sido bautizados en Cristo,
de Cristo estáis revestidos,`"^
footnote:[Gálatas 3:27]
no conceptualmente, sino realmente,
al ser sepultados con Él mediante este bautismo espiritual para muerte, es decir,
muerte al pecado.
"`A fin de que como Cristo resucitó de los muertos por la gloria del Padre,
así también nosotros andemos en vida nueva.`"^
footnote:[Romanos 6:4]
Y de nuevo, "`De modo que si alguno está en Cristo, nueva criatura es;
las cosas viejas pasaron; he aquí todas son hechas nuevas.`"^
footnote:[2 Corintios 5:17]
Y si todo proviene de Dios, no puede haber pecado, porque '`el pecado es del diablo,
no de Dios.`'^
footnote:[1 Juan 3:8]

Con respecto a la otra ceremonia, llamada la Cena del Señor,
estoy consciente del prejuicio profundamente arraigado a favor de esta.
Sin embargo, no me siento desanimado, creyendo que un glorioso día está amaneciendo,
cuando las nubes y sombras, señales y apariencias le darán lugar a la realidad,
a la sustancia pura y esencial.
Estoy perfectamente satisfecho en mi propia mente con respecto a esto,
y me esforzaré para dar mis razones por las que no creo que tenga
la importancia y obligatoriedad que muchos le atribuyen.

Que nuestro Señor, la noche antes de sufrir, tomó pan,
lo partió y se lo dio a Sus discípulos, y que también tomó la copa y dijo:
"`Haced esto en memoria de mí,`" definitivamente lo creo,
pero no encuentro que Él lo haya establecido como una ordenanza a seguir.
Supongo que se concederá que esta comida formaba
parte de la fiesta de la pascua de los judíos,
porque nuestro Señor dijo:
"`¡Cuánto he deseado comer con vosotros esta pascua antes que padezca!`"^
footnote:[Lucas 22:15], y que esta fiesta era un notable tipo o figura de Cristo,
quien era el propio Cordero Pascual, la sustancia o antitipo mismo.
Y supongo que también se concederá, que el pan y el vino, como parte de esa Pascua,
representaban el cuerpo y la sangre de Cristo,
que debían ser partido y derramada para la remisión de pecados.
Pero dado que definitivamente hay una diferencia
muy esencial entre la señal y la cosa señalada,
consideremos un poco cuál es de mayor consecuencia, o si ambas son obligatorias.
Espero que nadie a quienes me dirijo niegue que Cristo era y es, verdaderamente,
la sustancia y antitipo de cada tipo y figura bajo la dispensación ceremonial de Moisés.
Y puesto que esta es una de esas figuras que representan la muerte de Cristo;
ahora que la sustancia ha venido y el tipo se ha cumplido,
¿qué necesidad hay de la sombra?
¿Por qué no darle lugar a la sustancia,
como se hace libremente con otros símbolos y figuras?

El apóstol, escribiendo a los de Corinto, comenta: "`Así, pues,
todas las veces que comiereis este pan, y bebiereis esta copa,
la muerte del Señor anunciáis hasta que él venga.`"^
footnote:[1 Corintios 11:26]
Creo que esto de ninguna manera implica que esta fuera una ordenanza prescrita u obligatoria,
sólo muestra que aquellos a quienes él les estaba escribiendo,
continuaban con el uso o guardando la pascua judía.
No creo que esto deba considerarse improbable,
cuando se ve que por un tiempo fue enseñado por algunos de los discípulos,
"`es necesario circuncidarlos, y mandarles que guarden la ley de Moisés.`"^
footnote:[Hechos 15:5]
Por tanto, me parece que aquellos a quienes Pablo les escribió, todavía no sabían,
en un sentido espiritual, de la venida de Cristo; o sea,
de Su aparición espiritual en sus corazones.
Y parece que Lucas infiere un caso similar en Hechos 19:2,
donde habla de algunos que habían sido bautizados con el bautismo de Juan,
que es de agua, pero ni siquiera habían oído si había un Espíritu Santo,
la manera prometida de Su venida otra vez, mencionada en Juan 16:7,
"`Pero yo os digo la verdad: Os conviene que yo me vaya; porque si no me fuera,
el Consolador no vendría a vosotros; mas si me fuere, os lo enviaré.`"

De nuevo, el apóstol dice, hablándoles a los sabios (sin lugar a duda,
espiritualmente sabios): "`La copa de bendición que bendecimos,
¿no es la comunión de la sangre de Cristo?
El pan que partimos, ¿no es la comunión del cuerpo de Cristo?`"^
footnote:[1 Corintios 10:15-16]
¿Puede suponerse que él aluda aquí al pan y al vino externos?
Porque si lo hizo, entonces todos los que participan de esa ceremonia externa,
quienquiera que sean o lo que sean, pueden tener comunión con Cristo.
Esto, de seguro, sería unir luz con tinieblas, a Cristo con Belial,
justicia con injusticia,
en oposición directa a la clara declaración del apóstol a las mismas personas.^
footnote:[2 Corintios 6:15]
En otra parte dice: "`No podéis beber la copa del Señor, y la copa de los demonios;
no podéis participar de la mesa del Señor, y de la mesa de los demonios.`"^
footnote:[1 Corintios 10:20]
Ahora bien, es muy obvio que cualquiera puede participar del pan y del vino externos,
por tanto,
esas no pueden ser la copa ni la mesa del Señor. Y lo que se registra
en Hechos 2:46 de los discípulos partiendo el pan en las casas,
creo que por ningún medio implica tal ceremonia,
sino una manera social de vivir entre ellos.
Tal como es dicho en el versículo 44:
"`y tenían en común todas las cosas;`" y de lo que sigue inmediatamente:
"`comían juntos con alegría y sencillez de corazón,`"
aludiendo claramente a sus comidas en común.

También, creo que es muy notable,
que cuando los apóstoles se reunieron en Jerusalén para considerar
lo que era necesario prescribirles a los creyentes gentiles,
esta ceremonia de pan y vino ni siquiera fue mencionada.
Si hubiera sido necesaria, de seguro no se habría omitido,
teniendo en cuenta las cosas que se ordenaron en ese momento,
la mayoría de las cuales se han dejado de lado desde entonces, (es decir,
que "`se aparten de las contaminaciones de los ídolos, de fornicación,
de ahogado y de sangre.`"^
footnote:[Hechos 15:20]) Las propias palabras de nuestro Señor me parecen
decididamente desfavorables a la exigencia de una señal externa,
cuando enfáticamente se llama a Sí mismo en Juan 6:48, "`el pan de vida.`"
Y luego añade en Juan 6:54-55,
que cualquiera que comiera Su carne y bebiera Su sangre tendría vida eterna,
porque Su carne era verdadera comida y Su sangre verdadera bebida.
Y para reprender sus ideas carnales de comer y beber externamente (vers.
52), y dirigir sus mentes a la sustancia espiritual añade: "`¿Pues qué,
si viereis al Hijo del Hombre subir adonde estaba primero?`"
(vers.
62). Es como decir, ¿cómo Lo comerán entonces?
No en el pan ni en el vino externos, porque "`El espíritu es el que da vida;
la carne para nada aprovecha`" (vers.
63).

Creo que hay entre los que me dirijo,
algunos que son conscientes de la necesidad de esta comunión espiritual,
y que están verdaderamente deseosos de participar de ella.
¡Lejos está de mí herir a alguno de estos!
Yo los saludo con ternura,
y siento una medida de unidad con la más pequeña
aparición de la verdadera Semilla del reino.
No deseo herir la planta más pequeña del plantío del Señor. Sin embargo,
déjenme decir esto en un espíritu de amor y unidad:
Dado que se admite que esta no es más que una señal o símbolo, ¿por qué se continúa,
cuando se prescinde de otras de igual autoridad y obligación? Por ejemplo,
la de la circuncisión, a la que nuestro Señor mismo se sometió,^
footnote:[Lucas 2:21]
y que por un tiempo, incluso después de Su ascensión, fue prescrita por Sus discípulos,
como cité anteriormente.
¿Por qué fue dejada de lado esta?
Quizás se pueda responder, porque esta señal,
de acuerdo con la definición del apóstol de ella,
representaba la circuncisión "`no hecha a mano,
al echar de vosotros el cuerpo pecaminoso carnal.`"^
footnote:[Colosenses 2:11]
Creo plenamente que lo hizo,
y como es igualmente cierto que el pan y el vino son una señal,
no me parece que exista una razón por la que una deba continuar en preferencia de otra,
viendo que la cosa señalada en ambas es de igual obligación.

Además, es digno de observar, que el amado discípulo Juan, en su relato de esa noche,
no hace la menor mención del pan ni del vino,
pero es muy específico cuando da cuenta de que nuestro Señor lavó los pies de Sus discípulos.
Ahora, ¿por qué no es guardada __esa__ ceremonia en la iglesia de hoy,
pues parece incluso más particularmente prescrita que la otra?
Pues Cristo dice: "`Vosotros me llamáis Maestro, y Señor; y decís bien, porque lo soy.
Pues si yo, el Señor y el Maestro, he lavado vuestros pies,
vosotros también debéis lavaros los pies los unos a los otros.
Porque ejemplo os he dado, __para que como yo os he hecho, vosotros también hagáis.__`"^
footnote:[Juan 13:13-15]
Entonces, ¿dónde se puede hallar una orden tan fuerte para el pan y el vino?
Si se responde,
que el lavado de pies era una señal o figura para enseñar humildad y amor unos a otros,
lo cual de buena gana admito que lo era,
creo entonces necesario probar que la otra es algo más que
una señal para apoyar su continuidad y preferencia,
lo cual supongo que difícilmente se intentará.

Que la cena externa no era practicada u observada como una "`ordenanza`" por los apóstoles,
creo que es evidente en la totalidad del tenor de sus escritos.
De hecho, Pablo reprende a algunos por estar sujetos a ordenanzas, diciendo:
"`Pues si habéis muerto con Cristo en cuanto a los rudimentos del mundo, ¿por qué,
como si vivieseis en el mundo, os sometéis a preceptos tales como: No manejes, ni gustes,
ni aun toques (en conformidad a mandamientos y doctrinas de hombres),
cosas que todas se destruyen con el uso?`"^
footnote:[Colosenses 2:20-22]
¿Acaso no se destruyen con el uso el pan y el vino?
El apóstol sabía bien que el pan vivo y verdadero no era de una naturaleza perecedera.
Otra vez dice: "`Por tanto, nadie os juzgue en comida o en bebida,
o en cuanto a días de fiesta, luna nueva o días de reposo,
todo lo cual es sombra de lo que ha de venir; pero el cuerpo es de Cristo.`"^
footnote:[Colosenses 2:16-17]
En otro lugar dice: "`Porque el reino de Dios no es comida ni bebida, sino justicia,
paz y gozo en el Espíritu Santo.`"^
footnote:[Romanos 14:17]
Y a otros les dice: "`Me temo de vosotros,
que haya trabajado en vano con vosotros,`" porque "`conociendo a Dios, o más bien,
siendo conocidos por Dios,
¿cómo es que os volvéis de nuevo a los débiles y pobres rudimentos,
a los cuales os queréis volver a esclavizar?
Guardáis los días, los meses, los tiempos y los años,`"^
footnote:[Gálatas 4:9-11]
lo cual él había declarado que no era más que "`sombras de cosas buenas.`"
Me temo que el mismo lenguaje es muy aplicable a
muchos que profesan creer grandes cosas hoy.

A partir de lo que he observado sobre este tema, creo que para una mente sin prejuicios,
esto debe parecer: __Primero,__
que la verdadera cena del Señor es una comunión interna y espiritual;
"`He aquí,`" dice el Señor, "`yo estoy a la puerta y llamo;
si alguno oye mi voz y abre la puerta, entraré a él, y cenaré con él, y él conmigo.`"^
footnote:[Apocalipsis 3:20]
__Segundo,__ que el pan y el vino externos eran parte de la dispensación ceremonial judía,
los cuales no fueron ni mandados como ordenanza,
ni practicados por los gentiles en general, en los días de los apóstoles.
Y yo añadiría, que si efectivamente hubieran sido una ordenanza necesaria,
o en otras palabras, si fueran lo que muchos afirman que es,
entonces los efectos serían evidentes.
Porque nuestro Señor dijo: "`El que come mi carne y bebe mi sangre, tiene vida eterna.`"^
footnote:[Juan 6:54]
Presumo que nadie a quien me dirijo ahora,
le imputará tal efecto al pan y al vino externos.
¿Cómo, por tanto, puede ser esta la verdadera cena del Señor,
ya que en ninguna parte leemos de dos cenas?
Creo que muchos están en algún grado conscientes
de la diferencia entre la señal y la cosa misma,
la sombra y la sustancia.
Y al ver que se debe participar de la sustancia o de la realidad (sí,
es una necesidad absoluta, puesto que nuestro Señor dijo:
"`Si no coméis la carne del Hijo del Hombre, y bebéis su sangre,
no tenéis vida en vosotros`"^
footnote:[Juan 6:53]), entonces,
ciertamente es de gran importancia conocer correctamente cuál es la verdadera cena.

No tengo duda de que hay quienes que, con corazón sincero y recto,
continúan con el uso de la señal externa; ¡y lejos está de mí juzgarlos!
Sólo tengo una advertencia que dar en amor, que donde se guarda una señal,
sea como para el Señor y no para los hombres.^
footnote:[Romanos 14:6]
Creo plenamente,
que la religión no consiste en observar o no observar ceremonias externas.
Porque como dice el apóstol: "`En Cristo Jesús ni la circuncisión vale nada,
ni la incircuncisión, sino una nueva creación.`"^
footnote:[Gálatas 6:15]
No es un nombre, una profesión de fe o alguna práctica externa.
Sin embargo,
me temo que muchos guardan tales cosas como para los hombres y son esclavos de ellas,
y están tan asentados y a gusto en ellas,
que difícilmente oirán la menor objeción que se les haga.
Las personas de este tipo tal vez deban ser dejadas por un tiempo.

Así, pues, he dado algunas de mis razones por las que me separé de su comunión,
y del porqué creo que la adoración que se realiza
ahí no es la adoración que el Señor exige,
al no concordar con las Escrituras, sino contradecirlas.
No encuentro que dicha adoración sea (como se afirma) '`los
medios de gracia y la ordenanza de Dios,`' sino,
en gran medida, invención e imaginación del hombre,
al estar equivocada tanto en principio como en práctica.
En principio,
porque ustedes han sido enseñados que no deben esperar libertad del pecado en esta vida,
mientras las Escrituras unánimemente testifican lo contrario.
En práctica, porque adoran en sus propias voluntades,
y enseñan como doctrina mandamientos de hombres (contra
lo cual testifica nuestro Señor en Marcos 7:7),
sí, y en un estado no regenerado, según su propia confesión. De modo que,
lo que he escuchado entre ustedes,
que '`sus mejores servicios están contaminados,`' es exactamente cierto,
porque mientras continúen en un estado contaminado,
todas sus actuaciones estarán contaminadas también. Porque,
"`¿quién hará limpio a lo inmundo?
Nadie.`"^
footnote:[Job 14:4]
Sin embargo, puede ser bueno recordar, y que permanece como una verdad inmutable,
que "`el sacrificio de los impíos es abominación`"^
footnote:[Proverbios 21:27]
para el Señor. Aunque nos distraigamos con la vana idea de que todo está bien,
creo con certeza, que para ofrecer un sacrifico o un servicio aceptable,
debemos conocer (conocer por experiencia), que hemos sido "`lavados, santificados,
justificados en el nombre del Señor Jesús, y por el Espíritu de nuestro Dios.`"^
footnote:[1 Corintios 6:11]

Por tanto, recuerden el lenguaje de antaño a algunos que no tenían salud,
sino que estaban enfermos de la cabeza a los pies, como muchos confiesan estar ahora:
"`¿Para qué me sirve, dice Jehová, la multitud de vuestros sacrificios?
&hellip;No me traigáis más vana ofrenda; el incienso me es abominación;
luna nueva y día de reposo, el convocar asambleas, no lo puedo sufrir;
son iniquidad vuestras fiestas solemnes &hellip;Cuando extendáis vuestras manos,
yo esconderé de vosotros mis ojos; asimismo cuando multipliquéis la oración,
yo no oiré.`"^
footnote:[Isaías 1:11-15]
Y consideren la exhortación a ellos: "`Lavaos y limpiaos;
quitad la iniquidad de vuestras obras de delante de mis ojos; dejad de hacer lo malo;
aprended a hacer el bien,`"^
footnote:[Isaías 1:16-17]
etc.
Luego se añade: "`Si vuestros pecados fueren como la grana,
como la nieve serán emblanquecidos; si fueren rojos como el carmesí,
vendrán a ser como blanca lana.
Si quisiereis y oyereis, comeréis el bien de la tierra;
si no quisiereis y fuereis rebeldes, seréis consumidos a espada;
porque la boca de Jehová lo ha dicho.`"^
footnote:[Isaías 1:18-20]
¡Oh, qué terrible es esta denuncia, la cual se cumple ahora a nuestro alrededor!
Es la ferviente respiración de mi espíritu, que esta nación favorecida,
que profesa creer grandes verdades,
y que ha estado llamando abundantemente al Señor
con sus bocas y honrándolo con sus labios,
pueda evitar el inminente golpe humillándose delante
de Él. Y que mientras Sus juicios estén en la tierra,
ellos puedan efectivamente aprender justicia.^
footnote:[Isaías 26:9]

Sé, mis amigos, por cierto grado de experiencia, que hay muchas y varias apariencias,
símbolos y sombras establecidas entre los profesantes cristianos,
algunas de las cuales ya he señalado.
Ahora deseo dirigirlos, según mi medida actual con la que soy favorecido hoy,
a la realidad o sustancia misma.
Pues el inestimable tesoro que había sido por mucho tiempo y en vano buscado afuera,
entre esas varias apariencias, finalmente encontré que estaba adentro.
Puedo anticipar la sorpresa, y tal vez la indignación,
que la palabra "`adentro`" puede despertar en algunas mentes,
que pueden estar listas a exclamar: "`¿Puede haber algo bueno en el hombre?`"
Sí, amigos, el soberano bueno, el único bueno, se encuentra allí,
y deseo su paciente atención mientras me esfuerzo por eliminar esa idea injusta,
engañosa y destructiva, de que no se puede encontrar nada bueno en el hombre.

Creo que el gran artificio,
que la más exitosa insinuación del gran adversario de la humanidad es,
desviar la atención de lo único que es capaz de destruir
efectivamente su reino o gobierno en el corazón,
y arrastrar la mente a objetos afuera;
a las varias similitudes y apariencias en lo que
puede ser llamado '`Misterio de Babilonia.`' Entonces,
aunque esto '`bueno`' está en el hombre, __no es del hombre.__
No es natural en él, más bien es un don gratuito, espontáneo e inmerecido.
¿Qué es?
Con reverencia sea dicho: Es Dios mismo dado al alma del hombre;
una verdad de suma importancia, que todo individuo debe conocer por experiencia.
Y, de hecho, de esta verdad se testifica abundantemente en los escritos sagrados,
como la base, sustancia y fundamento de la religión real.
Las palabras que testifican de esta verdad son repetidamente
expresadas por todos los profesantes del cristianismo,
aunque la __verdad__ de esta, la __realidad__ de esta, parece muy poco conocida.
¿Acaso no leen con frecuencia: "`Habitaré y andaré entre ellos, y seré su Dios,
y ellos serán mi pueblo.`"^
footnote:[2 Corintios 6:16]
"`El que me ama,`" dijo nuestro Señor, "`mi palabra guardará; y mi Padre le amará,
y vendremos a él, y haremos morada con él.`"^
footnote:[Juan 14:23]
El Consolador "`el Espíritu de verdad,`" que procede del Padre, dijo,
"`mora con vosotros, y estará en vosotros.`"^
footnote:[Juan 14:17]
"`¿O no os conocéis a vosotros mismos, que Jesucristo está en vosotros,
a menos que estéis reprobados?`"^
footnote:[2 Corintios 13:5]
"`¿O ignoráis que vuestro cuerpo es templo del Espíritu Santo?`"^
footnote:[1 Corintios 6:19]

Yo podría multiplicar las citas de las Escrituras
para probar esta gran e importante verdad,
pero estoy consciente de que a los que me dirijo están bien familiarizados con las palabras.
Ustedes leen con frecuencia: "`Cristo en vosotros, la esperanza de Gloria,`"^
footnote:[Colosenses 1:27]
bajo varias figuras y tipos.
Pero, ¿cuál es la razón por la que Él no es conocido ahí? ¡Esta es una pregunta muy importante!
Aunque las Escrituras declaran tan a menudo que Cristo está adentro, repito,
¿cuál es la razón por la que (a pesar de tanto hablar e imaginación
sobre Él) muy pocos verdaderamente Lo experimentan ahí? Creo,
amigos, que puedo decirles la razón por la que Él, único gran Fundamento,
no es conocido en el único lugar donde puede ser verdaderamente conocido.
Porque __no es buscado ahí,__ sino en algo afuera,
en alguna apariencia o representación de Él,
en un conocimiento reunido de hombres o de libros, o de la historia o letra externa,
lo cual, por muy alto que se valore, es meramente conceptual.
El verdadero conocimiento es experimentado únicamente, por medio de Su aparición interna,
Su '`segunda aparición, sin pecado, para salvación,`'^
footnote:[Hebreos 9:28]
y la operación y efectos producidos por la misma.
Porque cuando Él aparece en Su templo, se sienta "`para afinar y limpiar la plata;
porque limpiará a los hijos de Leví, los afinará como a oro y como a plata,
y traerán a Jehová ofrenda en justicia.`"^
footnote:[Malaquías 3:3]

"`El reino de Dios,`" dijo nuestro Señor,
"`no vendrá con observación.`" El hombre con toda su sabiduría,
es incapaz de comprenderlo, "`ni dirán: Helo aquí, o helo allí; porque, he aquí,
el reino de Dios dentro de vosotros está.`"^
footnote:[Lucas 17:20-21 RV1602P]
El apóstol dijo: "`No digas en tu corazón: ¿Quién subirá al cielo?
(esto es, para traer abajo a Cristo); o, ¿quién descenderá al abismo?
(esto es, para hacer subir a Cristo de entre los muertos).`"
Él no está a cierta distancia, sino que, "`Cerca de ti está la palabra,
en tu boca y en tu corazón.`"^
footnote:[Romanos 10:6-8]

Nuestro Señor representó esta gran verdad por medio de varios objetos o semejanzas,
para transmitir instrucción espiritual a Sus discípulos.
Él habló de un tesoro escondido en un campo,^
footnote:[Mateo 13:44]
de una semilla sembrada en un terreno,^
footnote:[Marcos 4:26]
de un grano de mostaza,^
footnote:[Mateo 13:31]
de una pequeña medida de levadura escondida en la harina;^
footnote:[Mateo 13:33]
claramente aludiendo a este inestimable tesoro escondido en el corazón,
la parte terrenal del hombre.
Hubo algunos de quienes nuestro Señor dijo: "`Tienen oídos, pero no oyen.`"
Pero de otros dijo: "`A vosotros os es dado saber el misterio del reino de Dios.`"^
footnote:[Marcos 4:11]
Ahora, amigos, es de gran importancia saber de cuáles somos,
si Sus palabras son todavía para nosotros como parábolas,
o si conocemos eso que revela su verdadero significado.
"`Yo soy la luz del mundo;`" dijo Cristo, "`el que me sigue, no andará en tinieblas,
sino que tendrá la luz de la vida.`"^
footnote:[Juan 8:12]

Ahora, bien, el apóstol dice que no hay comunión entre la luz y las tinieblas.^
footnote:[2 Corintios 6:14]
Si nosotros no tenemos esta luz, necesariamente estamos en tinieblas.
Hay una luz espiritual, así como también una natural, y el gran apóstol de los gentiles,
al declarar su comisión de predicar a los gentiles,
dijo que tenía que testificar "`para que se conviertan de las tinieblas a la luz,
y de la potestad de Satanás a Dios.`"^
footnote:[Hechos 26:18]
¡Cuán importante es conocer esta luz,
la única por la que podemos discernir entre lo bueno y lo malo!
El apóstol dijo: "`Pero todas las cosas que son reprobadas,
son hechas manifiestas por la luz, porque lo que manifiesta todo, es la luz.`"^
footnote:[Efesios 5:13 RVG]
Las Escrituras hablan abundantemente de esta luz, para que podamos conocer qué es.
Juan el Bautista fue enviado para dar testimonio de esta luz verdadera,
la cual alumbra a todo hombre que viene al mundo (Juan 1:8-9). En Él, es decir,
en Cristo, estaba la vida,
y la vida era la luz de los hombres (Juan 1:4). Esta luz resplandece en las tinieblas,
o sea, en el corazón oscuro del hombre,
aunque las tinieblas no la pueden comprender (Juan 1:5). Esta es la luz
del glorioso evangelio que "`resplandeció en nuestros corazones,
para iluminación del conocimiento de la gloria de Dios en la faz de Jesucristo.`"^
footnote:[2 Corintios 4:6]

Por tanto, amigos,
les advierto que eviten referirse a ella como una luz del hombre natural,
o una nueva luz, como muchos han hecho.
Porque creo que esta misma luz, si se cree en ella y se obedece,
efectuará las mismas obras espirituales en el corazón, o en el hombre interior,
que hizo anteriormente en los cuerpos del pueblo de Israel.
Asimismo, creo que hay un gran peligro en hablar mal de la luz,
porque aquellos que lo hacen, confiesan que son extraños a ella, y por tanto,
están caminando en tinieblas, pues no hay más que una verdadera luz espiritual.
Y "`Si decimos que tenemos comunión con él, y andamos en tinieblas, mentimos,
y no practicamos la verdad; pero si andamos en luz, como él está en luz,
tenemos comunión unos con otros,
y la sangre de Jesucristo su Hijo nos limpia de todo pecado.`"^
footnote:[1 Juan 1:6-7]

Nuestro Señor claramente declaró, que "`todo aquel que hace lo malo,
aborrece la luz y no viene a la luz, para que sus obras no sean reprendidas.
Mas el que practica la verdad viene a la luz,
para que sea manifiesto que sus obras son hechas en Dios.`"^
footnote:[Juan 3:20-21]
Por eso, no es extraño que los que abogan por la necesidad del pecado (lo cual es malo),
también hablen contra esta luz, y la llamen por cualquier otro nombre para excusarse.
Porque las cosas que la luz manifiesta como malas,
son demasiado queridas como para separarse de ellas,
mientras ellos aún puedan persuadirse de que es seguro retenerlas.

Mis amigos, hablo por experiencia,
y fervientemente les recomiendo que se vuelvan a esta luz interior,
de todos los "`aquí está`" y "`allí está,`" de las varias apariencias,
señales y sombras establecidas por la voluntad y sabiduría de los hombre
en los tiempos de oscuridad y apostasía. Vuélvanse a Cristo en el interior,
la esperanza de gloria, el verdadero fundamento,
la roca contra la que (si permanecemos fielmente en ella)
incluso las puertas del infierno no prevalecerán,^
footnote:[Mateo 16:18]
ni toda la oposición de los hombres.
Creo que esto es la sustancia de toda sombra, la realidad de toda apariencia externa,
la Palabra que está cerca, en la boca y en el corazón, la verdadera unción,
la cual es verdadera y no es mentira,
y que enseña todas las cosas sin necesidad de la enseñanza de los hombres.^
footnote:[1 Juan 2:27]
Este es el nuevo pacto, misericordiosamente prometido por el Altísimo:
"`Daré mi ley en su mente, y la escribiré en su corazón; y yo seré a ellos por Dios,
y ellos me serán por pueblo.
Y no enseñará más ninguno a su prójimo, ni ninguno a su hermano, diciendo:
Conoce a Jehová; porque todos me conocerán,
desde el más pequeño de ellos hasta el más grande, dice Jehová.`"^
footnote:[Jeremías 31:33-34]

"`He aquí,`" dijo nuestro Señor, "`el reino de Dios dentro de vosotros está.`"^
footnote:[Lucas 17:21 RV1602P]
La semilla del reino que es sembrada en el corazón es demasiado
pequeña como para que el ojo de la sabiduría del hombre la descubra;
esta sigue siendo una piedra de tropiezo para el altivo profesante judío,
y locura para la sabiduría mundana del griego.
Pero los que oyen su llamado y lo obedecen, encuentran que es "`Cristo poder de Dios,
y sabiduría de Dios.`"^
footnote:[1 Corintios 1:23-24]
Creo que este es el nuevo nacimiento,
sin el cual (declaró nuestro Señor) nadie podía siquiera ver el reino de Dios,^
footnote:[Juan 3:3]
el nacimiento que no es de sangre, ni de la voluntad de la carne,
ni de la voluntad del hombre, sino de Dios.^
footnote:[Juan 1:13]
Porque lo que es nacido de la carne, sin importar cuán alto y atractivo parezca,
sigue siendo carne, y lo que es nacido del Espíritu,
por muy bajo y despreciable que le parezca al ojo de la sabiduría del hombre,
es Espíritu.

El evangelio es una dispensación espiritual.
Nuestro Señor prometió que el Espíritu de verdad, internamente manifestado,
guiaría a toda verdad.^
footnote:[Juan 16:13]
Los apóstoles no debían dejar Jerusalén hasta que lo hubieran recibido,^
footnote:[Hechos 1:4]
y luego se nos informa que "`comenzaron a hablar en otras lenguas,
según el Espíritu les daba que hablasen.`"^
footnote:[Hechos 2:4]
No tenemos razón para suponer que hayan usado alguna forma preparada de palabras,
ni que hablaran cuándo o dónde escogieran, más bien,
se nos habla con frecuencia de cómo viajaban o se
quedaban de acuerdo a lo que les indicaba el Espíritu;
ver Hechos 8:29; 19:8; etc.
Tampoco debemos suponer que esta influencia y dirección
del Espíritu se limitó a un período específico de tiempo;
porque nuestro Señor dijo: "`He aquí yo estoy con vosotros todos los días,
hasta el fin del mundo.`"^
footnote:[Mateo 28:20]
¡Qué desviación del ejemplo de ellos y del precepto es lamentablemente
evidente entre la mayoría de los profesantes cristianos de hoy!
Porque estos han inventado varias imágenes, formas y modos de adoración,
que pueden realizar cuando les plazca,
creyendo evidentemente que la influencia y asistencia del Espíritu son innecesarias,
o al menos, que ellos seguirán adelante sea que Él ayude o no.
De seguro, sería bueno considerar, si esto no es ofrecer fuego extraño delante del Señor.^
footnote:[Levítico 10:1]

La única verdadera adoración bajo la dispensación del evangelio es (en concordancia
con la declaración expresa de nuestro Señor) la que es "`en Espíritu y en verdad,`"^
footnote:[Juan 4:24]
y las influencias y movimientos del Espíritu (tan absolutamente necesarios,
que no se puede efectuar ninguna adoración aceptable
sin ellos) no están a nuestras órdenes.
¡Cuán apropiado, sí, cuán necesario es entonces, una humilde,
silenciosa y dependiente espera en Aquel que es el único que puede ministrar esta ayuda!
Allí se experimenta la verdadera preparación del corazón,
para recibir lo que Él (el que escudriña el corazón y el único que conoce
lo que es bueno para los que esperan en Él) se complazca en ministrar;
ya sea inmediatamente, mediante Su voz apacible y delicada en lo secreto del corazón,
o instrumentalmente, por medio de cualquiera que a Él le plazca designar.

"`Los que esperan en el Señor,`" dijo el profeta, "`renovarán sus fuerzas.`"^
footnote:[Isaías 40:31 LBLA]
Es la creencia profesa de la mayoría de las asambleas religiosas,
que es bueno esperar en el Señor. Pero creo que un poco de seria consideración,
puede determinar a quienes se aplica esta promesa en Isaías. ¿Se aplica a aquellos que,
en solemne y humilde silencio,
esperan sentir las influencias del Espíritu que instruyen
y habilitan qué ofrecer y cuándo hacerlo,
o qué recibir de la Fuente del bien?
O,
¿es para los que siempre están listos a comenzar (ya sea en una forma prescrita
o en el ejercicio de las propias habilidades naturales o adquiridas),
tengan o no la ayuda del Espíritu?
En realidad,
me parece que el significado claro y expreso del término
"`esperan,`" habla de una expectativa silenciosa y atenta,
por la que nos acercamos más intencionadamente a
la sagrada presencia de Aquel que escudriña el corazón,
trata la mente y exige la verdad en lo íntimo.
De seguro, Él no puede ser engañado o entretenido con las expresiones más persuasivas,
o con el lenguaje más elocuente,
porque Él ha condenado decididamente la práctica de acercarse
a Él con la boca y de honrarlo con los labios,
mientras el corazón está lejos de Él.^
footnote:[Isaías 29:13]
Por tanto, es necesario esperar,
esperar silenciosamente hasta recibir el poder espiritual,
para no ser como los que ofrecieron "`sacrificio de necios.`"
"`No te des prisa con tu boca,`" dijo el sabio,
"`ni tu corazón se apresure a proferir palabra delante de Dios;
porque Dios está en el cielo, y tú sobre la tierra; por tanto,
sean pocas tus palabras.`"^
footnote:[Eclesiastés 5: 1-2]
Y, "`porque separados de mí,`" dijo nuestro bendito Señor, "`nada podéis hacer.`"^
footnote:[Juan 15:5]

Sin embargo, la práctica de muchos que profesan seguirlo a Él,
evidentemente declara que ellos piensan que __pueden__ hacer mucho sin Él,
ya que en lo que se refiere a palabras y actuaciones externas, siempre están listos.
El apóstol claramente declaró, que nosotros no sabemos pedir como conviene,
y que el Espíritu nos ayuda en nuestra debilidad.^
footnote:[Romanos 8:26]
¿Qué son entonces todas las artes de composición y los poderes
de humana elocuencia sin la ayuda del Espíritu?
¿Acaso no son como metal que resuena, o címbalo que retiñe? Nuestro Señor dijo:
"`Y orando, no uséis vanas repeticiones, como los gentiles,
que piensan que por su palabrería serán oídos.`"^
footnote:[Mateo 6: 7]
Me temo que este consejo es muy aplicable,
no sólo a los que usan oraciones formales y prescritas,
sino también a los muchos que favorecen las actuaciones improvisadas,
porque ambos a menudo actúan como si orar consistiera en expresiones externas--una
idea repetidamente condenada en las Escrituras de Verdad.

El apóstol después de decir que nosotros no sabemos qué pedir, agrega:
"`El Espíritu mismo intercede por nosotros con gemidos indecibles.`"
Cristo llamó hipócritas a los que oraban para ser vistos por los hombres,
y ordenó a Sus discípulos a orar en secreto al Padre que ve en lo secreto.^
footnote:[Mateo 6:5-6]
El apóstol también recomienda orar "`en todo tiempo
con toda oración y súplica en el Espíritu.`"^
footnote:[Efesios 6:18]
En otro lugar exhorta a ser "`constantes en la oración,`"^
footnote:[Romanos 12:12]
y de nuevo, "`orad sin cesar.`"^
footnote:[1 Tesalonicenses 5:17]
A partir de todo esto,
creo que debe quedar claro que puede haber verdadera oración sin palabras,
y que puede haber palabras sin verdadera oración. No hay
duda de que algunos poseen habilidades considerables,
un flujo de palabras listo, una oratoria agradable y elocuente,
que pueden hablar en cualquier momento que lo deseen y decir lo que he oído que
llaman '`una excelente oración,`' sin esperar sentir la única influencia que
puede capacitar a '`orar con el Espíritu y con el entendimiento.`'^
footnote:[1 Corintios 14:15]
Pero aunque tales ejercicios pueden producir una emoción temporal,
tanto en el que habla como en el que oye,
me temo que se hallará que son un fuego de su propia leña, una mera apariencia,
y no efecto del carbón vivo del verdadero altar.^
footnote:[Isaías 6:6]
Las mismas observaciones son igualmente aplicables
a cualquier otra ejecución externa de adoración,
pública o privada, porque aunque puede afectar el oído externo,
o encender chispas de calor temporal,
si no procede de los movimientos directos y sensibles del Espíritu de verdad,
puede ser llamada correctamente "`culto voluntario.`"

También he tenido temor, de que el lenguaje de antaño, donde se decía:
"`Y ponían límite al Santo de Israel;`"^
footnote:[Salmo 78:41 RVG, RV1602P]
sea aplicable a la mayoría de las sociedades religiosas profesantes,
donde un hombre o grupo de hombres en particular,
se otorgan el derecho exclusivo de enseñar y predicar.
Creo que esta práctica es totalmente contraria a la dispensación del evangelio,
y a los ejemplos y preceptos homogéneos de Cristo y Sus apóstoles.
Porque creo plenamente, que ninguna autoridad, llamado, capacitación u ordenación humana,
puede hacer a una persona ministro de Cristo; de hecho, esto es prerrogativa de Cristo.
Pablo dijo que él había sido hecho apóstol: "`No de hombres ni por hombre,
sino por Jesucristo y por Dios el Padre.`"^
footnote:[Gálatas 1:1]
Como observé antes,
al ser la dispensación del evangelio una "`dispensación del Espíritu,`" los verdaderos
ministros de esta son ministros del Espíritu y no de la letra.
No son ministros de palabras únicamente, es decir, de las palabras de las Escrituras,
sino ministros de la "`Palabra de vida eterna,`" de esa "`Palabra que estaba en el principio,
que vive y permanece para siempre,`"^
footnote:[1 Pedro 1:23]
de la Palabra que "`es viva y eficaz&hellip;y discierne
los pensamientos y las intenciones del corazón.`"^
footnote:[Hebreos 4:12]
Las palabras pueden tener, y sin duda tienen, su utilidad,
en la medida que el Espíritu las trae a la memoria y les da expresión;
pero robar las palabras de las Escrituras (ver Jeremías
23:30-31) y ponerlas en una forma predeterminada,
por muy elocuentemente que sean dadas,
no creo que deba llamarse predicación del evangelio.
Aquellos que son particularmente llamados,
capacitados y enviados por Cristo (como creo que es todo verdadero ministro),
no se tomarán la libertad de predicar u orar cuando les plazca,
donde les plazca o lo que les plazca,
sino sólo cuando sean directamente movidos y dirigidos por el Espíritu
de Cristo internamente revelado (ver Gálatas 1:16),
el Único que conoce qué es necesario ministrar.
Tales ministros, así como han recibido de gracia, de gracia dan,
en concordancia con el mandamiento de nuestro Señor en Mateo 10:8,
sin ninguna expectativa de intereses temporales en absoluto.
Porque como ellos no se pertenecen a sí mismos,
no pueden disponer de su tiempo o talentos según sus propias voluntades,
sino según se complace en dirigir Aquel que los ha llamado.

Para concluir: Es mi esperanza que las pocas observaciones que he ofrecido ahora,
sean suficientes para demostrar la naturaleza interna
y espiritual de la dispensación del evangelio,
y que los símbolos y figuras, y todas las representaciones ceremoniales externas,
están totalmente abolidas de esa adoración que sólo
puede realizarse en Espíritu y en verdad.

Se espera que estas reflexiones también muestren que la
única capacitación necesaria para la adoración verdadera,
es la influencia y dirección del Espíritu de verdad internamente revelado,
y que esta ayuda necesaria no se limita a tiempos y lugares,
ni a ningún hombre o grupo de hombres en particular.
Y ya que el apóstol declaró:
"`Pero a cada uno le es dada la manifestación del Espíritu para provecho,`"^
footnote:[1 Corintios 12:7]
creo que no hay nadie que no tenga una porción suficiente, la cual,
si se atiende apropiadamente, los dirigirá a las sendas del verdadero juicio.
La Palabra, o sea, la Palabra de vida eterna, está cerca de todos, por tanto,
nadie necesita buscar instrucción en los hombres; sino que la misma unción,
si la mente se dirige simple y sin reservas a ella,
enseña todas las cosas y es verdadera.^
footnote:[1 Juan 2:7]
¿Acaso hay alguien que no haya sentido Sus reprimendas
secretas por el mal y Su aprobación por el bien?
Y teniendo (agradecidamente) un grado de experiencia
de la ayuda que viene de este verdadero Maestro,
sinceramente recomiendo que cada individuo le preste su atención cuidadosa,
incansable y fiel.

[.signed-section-signature]
John Spalding

[.signed-section-context-close]
Reading, 30 del mes siete de 1794.
